version: "3"

services:
  web:
    user: root
    restart: always
    build: .
    ports:
        - "8000:5000"
    volumes:
      - "./:/opt/API/"
    
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgis/postgis:14-3.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  redis:
    image: redis:5.0.3-alpine
    restart: always
    volumes:
      - .data/redis:/data
    expose:
      - '6379'
    ports:
      - '6379:6379'

volumes:
  dbdata: